### PR TITLE
media-practice2

### PR DESCRIPTION
**Pull request by m92henebury**
day 3 practice.

### CODE REVIEW

**Comment by rockygg** [comment]
You have an extra css file that you don't need (media-practice.css) so go ahead and delete that page then you should fix the media query conditions to change on `min-width: 768px` and `min-width: 375px`

**Comment by rockygg** [comment]
okay looks good but your media queries are still targeting max-width not min-width

**Comment by m92henebury** [comment]
ok i got it https://github.com/GeekwiseB2/practice-m92henebury/branches

**Comment by rockygg** [comment]
:+1:

**Pull request merged**
